main:
  restart: always
  build: .
  environment:
    - MYDOMAIN=www.frandle.work:8888
    - KAKUYOMUDOMAIN=https://kakuyomu.jp
    - NOVELURL=https://kakuyomu.jp/works/1177354054882154317
  ports:
    - 8888:5000
